server:
  servlet:
    #项目名
    context-path: /
  port: 8082 #端口
    
 
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vue_boot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mappers/*/*.xml #映射文件路径
  type-aliases-package: com.vueboot.system.entity # pojo别名扫描包
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
